# Generated by Django 5.1.3 on 2024-12-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyMembers', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='familyMembers.familymember'),
            preserve_default=False,
        ),
    ]
