# Generated by Django 5.1.3 on 2024-12-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name_plural': 'Family Members'},
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='name',
        ),
    ]
