# Generated by Django 5.1.3 on 2024-12-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyMembers', '0003_family_familymember_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
